#!/bin/bash
isExistApp = `pgrep httpd`
if [[ -n  $isExistApp ]]; then
    service httpd stop        
fi
isExistApp = `pgrep tomcat7`
if [[ -n  $isExistApp ]]; then
    service tomcat7 stop        
fi
